### ISSUE TITLE
Need a few new entry points

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/APSoil#10]
The Apsoil web service has a rather long history, covering a period of time in which the underlying Apsoil format has changed. As a consequence, some of the functions expect data in one of the older formats, rather than the current one. As far as I can determine the different file formats include an old JSON version, an XML version, and an updated XML version. The older formats need to continue to be supported, as existing apps may rely on those formats. However, adding a few additional entry points to better support the "new" XML format will simplify development of new apps, such as an updated version of SoilMapp. Specifically, functions are needed to allow uploading of user soils in the "new' format, and also to allow the generation of PNG charts based on that format.

**Comment by ric394** [comment]
@zur003 these updates have been put on apsimdev.apsim.info.

**Comment by zur003** [comment]
@ric394 - Going to [https://github.com/APSIMInitiative/APSoil/issues/10](https://github.com/APSIMInitiative/APSoil/issues/10) still doesn't show the new WebMethods. Does something need to be restarted?

**Comment by ric394** [comment]
I can see the new web methods now @zur003 if you want to give them a try.

**Comment by zur003** [comment]
Re-opening since my changes weren't quite correct. I neglected to allow for the need to use HTML-encoding to send XML to the Web service (and likewise the need for the service to HTML-decode the text).
