### ISSUE TITLE
Issues with KMZ download

### ISSUE THREAD

**Issue by gdurri** [APSIMInitiative/APSoil#8]
Hi, I am trying to download the KMZ file to view the soils in Google Earth as my existing copy of this file is not longer working correctly. 

When I click the 'Click here to view the APSoil database in Google Earth.' link on the APSoil page, the link never loads and eventually returns a site can't be reached error. I have tried this in several browsers and on another computer with the same problem each time. Is the download not working at the moment/ is there another way to get access to this file?

Thank you in advance!

**Comment by hol353** [comment]
Yes our server is down - we're working on it. Hopefully it'll be back up today. 

The KMZ file we produce relies on the server being present so there is no workaround for getting you access quickly.

**Comment by gdurri** [comment]
Thanks for your reply! Good to know it's not just me, will wait for everything to get back up and running.

**Comment by hol353** [comment]
Should be fixed now.
